"""
analyze_change.py

This script takes a Changelist (CL) directory generated by `load_change.py`,
reads all the files within it (skipping files over 5000 lines), and uses the
Gemini REST API to analyze the change.

It uses standard library modules only, meaning no external dependencies (like pip)
are required. It prompts the Gemini model to generate a summary and
recommend additional files to include for a thorough review.

The output is saved to a `pre_review` file inside the CL directory.

Usage: python3 analyze_change.py <cl-dir-number>
"""

import os
import sys
import json
import urllib.request
import urllib.error

def get_file_contents(cl_dir):
    contents = []
    # Walk through the directory to find all downloaded files (diff, commit_info, original files)
    for root, dirs, files in os.walk(cl_dir):
        for file in files:
            file_path = os.path.join(root, file)

            # Skip the pre_review file if it already exists to avoid recursive prompting
            if file == "pre_review":
                continue

            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    lines = f.readlines()
                    if len(lines) > 5000:
                        print(f"Skipping {file_path} (more than 5000 lines)")
                        continue

                    file_content = "".join(lines)
                    contents.append(f"--- File: {file_path} ---\n{file_content}\n")
            except UnicodeDecodeError:
                print(f"Skipping {file_path} (binary or non-UTF-8 content)")
            except Exception as e:
                print(f"Skipping {file_path} due to error: {e}")
    return contents

def call_gemini_api(api_key, model_name, text_payload):
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={api_key}"

    headers = {
        "Content-Type": "application/json"
    }

    data = {
        "contents": [{
            "parts": [{"text": text_payload}]
        }],
        "generationConfig": {
            "temperature": 0.2
        }
    }

    req = urllib.request.Request(url, data=json.dumps(data).encode('utf-8'), headers=headers, method='POST')

    try:
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode('utf-8'))
            # Extract the text from the response structure
            try:
                return result['candidates'][0]['content']['parts'][0]['text']
            except (KeyError, IndexError):
                print("Unexpected response structure from Gemini API:")
                print(json.dumps(result, indent=2))
                return None
    except urllib.error.HTTPError as e:
        error_body = e.read().decode('utf-8')
        print(f"HTTP Error {e.code}: {e.reason}")
        print(f"Details: {error_body}")
        return None
    except Exception as e:
        print(f"Failed to communicate with Gemini API: {e}")
        return None

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 analyze_change.py <cl-dir>")
        sys.exit(1)

    cl_dir = sys.argv[1]
    if not os.path.isdir(cl_dir):
        print(f"Error: Directory '{cl_dir}' does not exist.")
        sys.exit(1)

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("Error: GEMINI_API_KEY environment variable not set.")
        sys.exit(1)

    print(f"Reading files in '{cl_dir}'...")
    file_contents = get_file_contents(cl_dir)
    if not file_contents:
        print("No valid files found to analyze.")
        sys.exit(1)

    document_text = "\n".join(file_contents)

    prompt_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "preview_change_prompt.md")
    try:
        with open(prompt_path, "r", encoding="utf-8") as f:
            prompt = f.read()
    except Exception as e:
        print(f"Error reading prompt file from {prompt_path}: {e}")
        sys.exit(1)

    full_payload = prompt + document_text + "\n--- END CONTEXT ---"

    model_name = 'gemini-3-flash-preview'

    print("Sending request to Gemini API (this may take a few moments)...")
    response_text = call_gemini_api(api_key, model_name, full_payload)

    if not response_text:
        print("Failed to get analysis from Gemini API.")
        sys.exit(1)

    try:
        # Strip potential markdown code blocks if the model still includes them
        clean_text = response_text.strip()
        if clean_text.startswith("```json"):
            clean_text = clean_text[7:]
        if clean_text.endswith("```"):
            clean_text = clean_text[:-3]

        result_data = json.loads(clean_text)

        summary = result_data.get("summary", "Summary not provided.")
        extra_files = result_data.get("extra_context_files", [])

        # Save summary
        summary_file = os.path.join(cl_dir, "summary")
        with open(summary_file, "w", encoding="utf-8") as f:
            f.write(summary)

        # Save extra_context_files
        extra_files_file = os.path.join(cl_dir, "extra_context_files")
        with open(extra_files_file, "w", encoding="utf-8") as f:
            for file_path in extra_files:
                f.write(f"{file_path}\n")

        print(f"\nAnalysis complete!")
        print(f"Saved summary to {summary_file}")
        print(f"Saved context files to {extra_files_file}")

    except json.JSONDecodeError as e:
        print("Error: The model did not return a valid JSON response.")
        print(f"Raw output:\n{response_text}")
        sys.exit(1)

if __name__ == "__main__":
    main()
