"""
load_extra_context.py

This script takes a Changelist (CL) directory generated by `load_change.py`
and `analyze_change.py`. It reads the `commit_info` file to determine the
Gerrit host and Change ID, and the `extra_context_files` file to get a list
of additional file paths.

It then uses the Gerrit REST API to download the contents of these additional
files (from the base commit/parent=1) and saves them into the CL directory,
preserving their directory structure.

Usage: python3 load_extra_context.py <cl-dir-number>
"""

import sys
import os
import re
import urllib.parse
import urllib.request
import base64

def get_gerrit_base64_bytes(url):
    req = urllib.request.Request(url)
    with urllib.request.urlopen(req) as response:
        encoded_data = response.read()
        return base64.b64decode(encoded_data)

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 load_extra_context.py <cl-dir>")
        sys.exit(1)

    cl_dir = sys.argv[1]

    if not os.path.isdir(cl_dir):
        print(f"Error: Directory '{cl_dir}' does not exist.")
        sys.exit(1)

    commit_info_path = os.path.join(cl_dir, "commit_info")
    extra_files_path = os.path.join(cl_dir, "extra_context_files")

    if not os.path.exists(commit_info_path):
        print(f"Error: {commit_info_path} not found.")
        sys.exit(1)

    if not os.path.exists(extra_files_path):
        print(f"Error: {extra_files_path} not found.")
        sys.exit(1)

    # 1. Parse commit_info to get the host and change_id
    host = None
    change_id = None

    with open(commit_info_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.startswith("Commit URL:"):
                commit_url = line.split("Commit URL:")[1].strip()
                # Example URL: https://chromium-review.googlesource.com/c/chromium/src/+/7652046
                match = re.search(r'https://([^/]+)/.*/\+/(\d+)', commit_url)
                if match:
                    host = match.group(1)
                    change_id = match.group(2)
                break

    if not host or not change_id:
        # Fallback to trying to use the directory name as the change ID and a default host
        print("Could not parse Commit URL from commit_info. Using defaults.")
        change_id = os.path.basename(os.path.normpath(cl_dir))
        host = "chromium-review.googlesource.com" # Default fallback

    base_api_url = f"https://{host}/changes/{change_id}"

    # 2. Read extra_context_files
    with open(extra_files_path, "r", encoding="utf-8") as f:
        files_to_download = [line.strip() for line in f if line.strip()]

    if not files_to_download:
        print("No files found in extra_context_files.")
        sys.exit(0)

    # 3. Download each file via Gerrit REST API
    print(f"Fetching {len(files_to_download)} extra context files...")
    for file_path in files_to_download:
        # File path must be URL encoded (e.g., / becomes %2F)
        encoded_path = urllib.parse.quote(file_path, safe='')
        content_url = f"{base_api_url}/revisions/current/files/{encoded_path}/content?parent=1"

        try:
            original_bytes = get_gerrit_base64_bytes(content_url)
            local_file_path = os.path.join(cl_dir, file_path)

            # Create subdirectories matching the file path structure
            os.makedirs(os.path.dirname(local_file_path), exist_ok=True)

            with open(local_file_path, "wb") as out_f:
                out_f.write(original_bytes)
            print(f"- Saved: {local_file_path}")
        except urllib.error.HTTPError as e:
            print(f"- Failed to fetch '{file_path}' (HTTP {e.code}: {e.reason})")
        except Exception as e:
            print(f"- Failed to fetch '{file_path}': {e}")

if __name__ == "__main__":
    main()
